/**
* HTTP strings used for the webserver
* Source for these strings can be found in the webpages directory
* Each string is a minified version of the web page
* Uses https://www.npmjs.com/package/html-minifier
* html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-css true --minify-js true [sourcefile] > [minified-file]
**/
#ifndef webpages_h
#define webpages_h
// root page - from deviceinit.html
String deviceinit_page = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>Initialize WeatherBird Device</title><link rel=\"stylesheet\"href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\"integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\"crossorigin=\"anonymous\"><script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"crossorigin=\"anonymous\"></script><script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\"integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\"crossorigin=\"anonymous\"></script><script src=\"https://www.gstatic.com/firebasejs/8.2.2/firebase-app.js\"></script><script src=\"https://www.gstatic.com/firebasejs/8.2.2/firebase-auth.js\"></script><script src=\"https://www.gstatic.com/firebasejs/8.2.2/firebase-database.js\"></script><script src=\"https://www.gstatic.com/firebasejs/ui/4.7.1/firebase-ui-auth.js\"></script><link type=\"text/css\"rel=\"stylesheet\"href=\"https://www.gstatic.com/firebasejs/ui/4.7.1/firebase-ui-auth.css\"><script type=\"text/javascript\">\
var firebaseConfig={apiKey:\"AIzaSyBoXs2I_0ciXdz8BkArQ2jB7nryhfyod78\",authDomain:\"weather-2a8a7.firebaseapp.com\",databaseURL:\"https://weather-2a8a7.firebaseio.com\",projectId:\"weather-2a8a7\",storageBucket:\"weather-2a8a7.appspot.com\",messagingSenderId:\"204321913040\",appId:\"1:204321913040:web:1bb1efc83e902b2da546d5\"};async function setupUser(e){try{return await firebase.database().ref(\"users/\"+e+\"/isPerson\").set(!0),!0}catch(e){return $(\"#errormsg\").html(\"<h3>Error occured initializing user access.  Please try again later.</h3>\"),!1}}firebase.initializeApp(firebaseConfig);var retryCount=0;function checkStatusUpdate(){retryCount>5&&displayInitializeFail(\"Unable to verify the Firebase was setup correctly\"),$.getJSON(\"status.json\").done(e=>{e.config.firebase_initialized?window.location.href=\"http://weather.sourceauditor.com\":7==e.state?displayInitializeFail(\"Error setting station owner - make sure it is not already owned\"):3==e.state?(retryCount++,checkStatusUpdate()):displayInitializeFail(\"Weatherstation was in an invalid state \"+e.state)}).fail(()=>{displayInitializeFail(\"Error getting status\")})}function displayInitializeFail(e){$(\"#errormsg\").html(e),$(\"#message\").html('WeatherBird Initialized Failed:<div class=\"container\"><a class=\"btn btn-primary\" href=\"/\" role=\"button\">Retry</a>&nbsp<a class=\"btn btn-secondary\" href=\"/cancel.html\" role=\"button\">Cancel</a></div>')}var uiConfig={callbacks:{signInSuccessWithAuthResult:function(e,i){setupUser(e.user.uid).then(i=>($(\"#message\").html(\"Please wait while the WeatherBird Weather Station initializes.\"),$.get(encodeURI(\"/userloggedin.html?uid=\"+e.user.uid),function(e,i){\"success\"==i?(retryCount=0,checkStatusUpdate()):(console.log(\"Error completing config: \"+i),displayInitializeFail(e))}).fail(function(){console.log(\"Failed userlogged in call\"),displayInitializeFail(\"Unable to set owner in the Weatherbird Station\")}),i))}},signInSuccessUrl:\"/deviceinitializing.html\",signInOptions:[firebase.auth.EmailAuthProvider.PROVIDER_ID],tosUrl:\"https://docs.google.com/document/d/1gVrImrv7k9SNVkKI_om6z0ft7x6aiWDs5icgMyeHPlk/edit?usp=sharing\",privacyPolicyUrl:function(){window.location.assign(\"https://docs.google.com/document/d/1OMp281bz8U0IiOM4q3a5eKF9XiBt65nCFt6oNsmw3n0/edit?usp=sharing&resourcekey=0-u8-Aq86I_ZQ2dAoroKlZ1Q\")}},ui=new firebaseui.auth.AuthUI(firebase.auth());ui.start(\"#firebaseui-auth-container\",uiConfig);\
</script></head><body><h1 class=\"d-flex justify-content-center\">Initialize Weatherbird</h1><div class=\"d-inline-flex p-2\"id=\"message\">Sign in or register using one of the methods below. Once you are signed in, the WeatherBird device will be registered and you will be able to access the device at http://weather.sourceauditor.com.</div><div id=\"firebaseui-auth-container\"></div><div id=\"errormsg\"></div></body></html>";
String cancel_page = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>WeatherBird Initialization Failed</title><link rel=\"stylesheet\"href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\"integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\"crossorigin=\"anonymous\"><script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"crossorigin=\"anonymous\"></script><script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\"integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\"crossorigin=\"anonymous\"></script></head><body><h1>WeatherBird Configuration Cancelled</h1>Weather information will display on the WeatherBird station but will not be available on the website or web application. Press the reset button to restart the initialization.</body></html>";
// Up until select network table rows
const char CONFIG_WIFI_PAGE1[] /*PROGMEM*/ = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>Network Config</title><style>.justify-content-center{justify-content:center!important}.d-flex{display:flex!important}.h1,h1{font-size:2.5rem;margin-block-start:.67em;margin-block-end:.67em;margin-inline-start:0;margin-inline-end:0}.h1,.h2,.h3,.h4,.h5,.h6,h1,h2,h3,h4,h5,h6{margin-bottom:.5rem;font-weight:500;line-height:1.2}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff}.roundedborder{border:1px solid #ccc!important;border-radius:8px;margin:10px;padding:5px}button,input{border-radius:4px;margin:5px}</style><script type=\"text/javascript\">\
function selectNetwork(e){document.getElementById(\"ssid\").value=e}function getStatus(){const e=new XMLHttpRequest;e.open(\"GET\",\"status.json\",!0),e.responseType=\"json\",e.addEventListener(\"load\",function(t){if(200==e.status){let t=e.response;t.ssid?(document.getElementById(\"message\").innerHTML=\"Connected to \"+t.ssid+\" \"+t.localIp,document.getElementById(\"btExit\").innerHTML=\"Exit Config\"):(document.getElementById(\"message\").innerHTML=\"Station not connected to internet\",document.getElementById(\"btExit\").innerHTML=\"Get Connection Status\")}else document.getElementById(\"message\").innerHTML=\"<strong>Error getting device status - please retry</strong>\",document.getElementById(\"btExit\").innerHTML=\"Get Connection Status\"}),e.addEventListener(\"error\",function(e){document.getElementById(\"message\").innerHTML=\"<strong>Error updating SSID configuration</strong>\"}),e.send()}function sendData(e){const t=new XMLHttpRequest,n={slot:e,ssid:document.getElementById(\"ssid\").value,password:document.getElementById(\"password\").value};t.addEventListener(\"load\",function(o){let s=\"slot\"+e.toString();\"Failed\"==t.getResponseHeader(\"X-Connection-Status\")?document.getElementById(\"message\").innerHTML=`<strong>Could not connect to ${n.ssid}</strong>`:(document.getElementById(s).innerHTML=`<h4>Slot ${e} SSID: ${n.ssid}</h4>`,document.getElementById(\"ssid\").value=\"\",document.getElementById(\"password\").value=\"\",setTimeout(()=>{getStatus()},1e3))}),t.addEventListener(\"error\",function(e){document.getElementById(\"message\").innerHTML=\"<strong>Error updating SSID configuration</strong>\"}),t.open(\"POST\",\"confignetwork\",!0),t.setRequestHeader(\"Content-Type\",\"application/json\"),t.send(JSON.stringify(n))}function exit(){const e=new XMLHttpRequest;e.addEventListener(\"load\",function(e){window.location.replace(\"/\")}),e.addEventListener(\"error\",function(e){document.getElementById(\"message\").innerHTML=\"<strong>Error exiting SSID configuration</strong>\"}),e.open(\"POST\",\"confignetwork\",!0),e.setRequestHeader(\"Content-Type\",\"application/json\"),e.send(JSON.stringify({exit:!0}))}window.onload=function(){document.getElementById(\"btExit\").addEventListener(\"click\",function(e){e.preventDefault(),\"Exit Config\"==document.getElementById(\"btExit\").innerHTML?exit():getStatus()});let e=0,t=\"btSlot\"+e,n=document.getElementById(t);for(;n;){const o=e;n.addEventListener(\"click\",function(e){e.preventDefault(),sendData(o)}),t=\"btSlot\"+ ++e,n=document.getElementById(t)}};</script></head><body><h1 class=\"d-flex justify-content-center\">Select Network</h1><div class=\"roundedborder\"><table><tr><th>SSID</th><th>Signal</th><th>Secured</th></tr>";
// Each SSID has the form "<tr><td><a href="#"onclick='selectNetwork("Network 1")'>Network 1</a></td><td>151</td><td>Open</td></tr>"
const char CONFIG_WIFI_PAGE_SSIDS[] /*PROGMEM*/ = "<tr><td><a href=\"#\"onclick='selectNetwork(\"{{S}}\")'>{{S}}</a></td><td>{{R}}</td><td>{{X}}</td></tr>";
// After network table rows until SSID slots
const char CONFIG_WIFI_PAGE2[] /*PROGMEM*/ = "</table></div><div class=\"roundedborder\">";
// Each slot has the form "<div id="slot1"><h4>Slot 1 SSID: SLOT1SSID</h4></div>"
const char CONFIG_WIFI_PAGE_SLOTS[] = "<div id=\"slot{{X}}\"><h4>Slot {{X}} SSID: {{S}}</h4></div>";
// After SSID slots and before the buttons
const char CONFIG_WIFI_PAGE3[] /*PROGMEM*/ = "</div><form id=\"nwconfig\"class=\"roundedborder\"><table><tr><td><label for=\"ssid\">SSID:</label></td><td><input type=\"text\"id=\"ssid\"><br></td></tr><tr><td><label for=\"password\">Password:</label></td><td><input type=\"text\"id=\"password\"><br></td></tr></table><div class=\"d-flex justify-content-center\">";
// Buttons are of the form "<button type="submit"form="nwconfig"id="slot1"onclick="sendData(1)">Add to Slot 1</button>"
const char CONFIG_WIFI_PAGE_BUTTONS[] = "<button type=\"submit\"form=\"nwconfig\"id=\"btSlot{{X}}\">Add to Slot {{X}}</button>";
// After buttons
const char CONFIG_WIFI_PAGE4[] /*PROGMEM*/ = "</div><div class=\"d-flex justify-content-center\"><button type=\"submit\"form=\"nwconfig\"id=\"btExit\">Get Connection Status</button></div></form><div id=\"message\"></div></body></html>";
#endif
